import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import { Analytics } from "@vercel/analytics/next";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";


export const metadata: Metadata = {
  title: "Kyzec Videography",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="overflow-x-hidden">
                <Analytics />
                <main id="content-wrapper" className="min-h-screen">
                  {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
