import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import { Analytics } from "@vercel/analytics/next";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";


export const metadata: Metadata = {
  title: "Kyzec Videography",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Head>
                <meta property="og:title" content="The Rock" />
                <meta property="og:url" content="https://www.jmai.photos" />
                <meta property="og:image" content="https://www.jmai.photos/whiteicon.png" />
            </Head>
            <body className="overflow-x-hidden">
                <Nav theme="dark" />
                <Analytics />
                {children}
                <Footer />
            </body>
        </html>
    );
}
